runtime: python313

handlers:
- url: /static
  static_dir: static
- url: /(robots\.txt)$
  static_files: misc/\1
  upload: misc/robots\.txt$
- url: .*
  script: auto

automatic_scaling:
  max_instances: 20

