runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
- url: /(robots\.txt)$
  static_files: misc/\1
  upload: misc/robots\.txt$
- url: .*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"
- name: lxml
  version: "latest"
